#!/usr/bin/env bash
# Power VPN Panel installer (SQLite edition)
#
# Run from the project root after cloning:
#   bash install.sh
#
# This script never overwrites an existing .env. It generates strong
# secrets, hashes the admin password with bcrypt, and writes both to
# .env (mode 600) plus a one-time .panel_credentials.txt for human use.

set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

ENV_FILE=".env"
CRED_FILE=".panel_credentials.txt"

# --- 1. Sanity checks ------------------------------------------------------
need() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "ERROR: '$1' is required but was not found in PATH." >&2
        exit 1
    }
}
need node
need npm

NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]')
if (( NODE_MAJOR < 18 )); then
    echo "ERROR: Node.js >= 18 required (found $(node -v))." >&2
    exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
    echo "Refusing to overwrite existing .env. Move it aside and re-run." >&2
    exit 1
fi

# --- 2. Collect admin credentials -----------------------------------------
echo "--- Power VPN Panel installation ---"
read -rp "Enter admin username (min 5 chars): " ADMIN_USER
until [[ ${#ADMIN_USER} -ge 5 ]]; do
    read -rp "Username too short. Try again: " ADMIN_USER
done

random_secret() {
    LC_ALL=C tr -dc 'A-Za-z0-9!@#%^&*()_+-' < /dev/urandom | head -c "${1:-24}"
}

read -rsp "Enter admin password (leave blank for a generated one): " ADMIN_PASS
echo
if [[ -z "$ADMIN_PASS" ]]; then
    ADMIN_PASS=$(random_secret 20)
    echo "→ generated a random admin password (saved to $CRED_FILE)."
fi

read -rp "Allowed CORS origins (comma-separated, default: http://localhost:3000): " CORS_ORIGINS
CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}

# --- 3. Install dependencies ----------------------------------------------
echo "→ installing npm packages (this may take a minute)…"
npm ci || npm install

# --- 4. Generate secrets ---------------------------------------------------
echo "→ hashing admin password with bcrypt…"
ADMIN_HASH=$(node -e "
const bcrypt = require('bcryptjs');
process.stdout.write(bcrypt.hashSync(process.argv[1], 12));
" "$ADMIN_PASS")

# 64-char hex = 32 bytes = exactly what jose / HMAC-SHA-256 expect.
JWT_SECRET=$(node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))")

# --- 5. Write .env ---------------------------------------------------------
umask 077
cat > "$ENV_FILE" <<EOF
# Power VPN Panel — generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
NODE_ENV=production
PORT=3000

# --- Admin credentials -------------------------------------------------------
ADMIN_USERNAME=$ADMIN_USER
ADMIN_PASSWORD_HASH=$ADMIN_HASH

# --- Crypto ------------------------------------------------------------------
# Used by the JWT session signer (jose). Must be >= 32 chars.
JWT_SECRET=$JWT_SECRET

# --- CORS --------------------------------------------------------------------
# Comma-separated origins, or '*' to allow all (the dedicated app talks to
# the API from a different origin, so set this accordingly).
ALLOWED_ORIGINS=$CORS_ORIGINS

# --- Database ----------------------------------------------------------------
# Power VPN uses an embedded SQLite file (panel.sqlite) in the project root.
# Nothing else to configure.
EOF

cat > "$CRED_FILE" <<EOF
--- Power VPN Panel credentials (KEEP SAFE — delete after saving) ---
Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

Admin username:       $ADMIN_USER
Admin password:       $ADMIN_PASS
JWT_SECRET (in .env): $JWT_SECRET

The hashed password lives in .env as ADMIN_PASSWORD_HASH. The plain
password above is only printed here so you can record it.
EOF

# --- 6. Build --------------------------------------------------------------
echo "→ building production bundle…"
npm run build

# --- 7. Done ---------------------------------------------------------------
echo
echo "----------------------------------------------------"
echo "Install complete."
echo "  • .env written (mode 600)"
echo "  • $CRED_FILE saved (mode 600) — read it once, then delete."
echo "  • SQLite DB will be created at panel.sqlite on first request."
echo
echo "Start the panel with:"
echo "  npm start"
echo
echo "or run it in Docker with:"
echo "  docker compose up -d"
echo "----------------------------------------------------"
